In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder,OrdinalEncoder


In [3]:
import sklearn
print(f"sklearn version : {sklearn.__version__}")

sklearn version : 1.7.2


In [4]:
X = np.array(["chien","chien","chat","oiseau"])

In [6]:
encoder = LabelEncoder()
encoder.fit(X)
encoder.transform(X)

array([1, 1, 0, 2])

In [7]:
X_new = np.array(["oiseau","oiseau","chien"])


encoder.transform(X_new)

array([2, 2, 1])

# OrdinalEncoder()

et

# OnehotEncoder()

In [9]:
df = sns.load_dataset("diamonds")
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [17]:
df['clarity'].unique()

['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF']
Categories (8, object): ['IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1']

In [22]:
cut_oder =['very bad','bad','Fair','Good','Very Good','Premium','Ideal']
color_order =['J','I','H','G','F','E','D']
clarity_order =['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

encoder = OrdinalEncoder(
    categories=[cut_oder,color_order,clarity_order],
    handle_unknown="use_encoded_value",
    unknown_value=-1,                     
                         )
encoder.fit_transform(df[["cut","color","clarity"]])

array([[6., 5., 1.],
       [5., 5., 2.],
       [3., 5., 4.],
       ...,
       [4., 6., 2.],
       [5., 2., 1.],
       [6., 6., 1.]], shape=(53940, 3))

In [23]:
encoder.transform([['bad','G','SI1']])

/home/romaric420/Analyse/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[1., 3., 2.]])

In [24]:
df = sns.load_dataset("mpg")
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [32]:
encoder = OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore')
encoder.fit_transform(df[["origin"]])

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.

In [27]:
df["origin"].unique()

array(['usa', 'japan', 'europe'], dtype=object)

# encoder une target 

In [34]:
X = df[['mpg','cylinders','displacement','horsepower','weight','acceleration']]
Y = df['origin']
